-- ============================================================================
-- Board-Prep Agent — Supabase schema (init migration 0001)
-- ----------------------------------------------------------------------------
-- Realises the data model in requirements §7 + §14.7. Column comments cite the
-- requirement / entity each table serves. This migration is the substrate (M9);
-- the Supabase repository (repo_supabase.py) round-trips the domain.py pydantic
-- models against these tables.
--
-- DESIGN DECISIONS baked in here (flagged in chat for confirmation):
--   D1  Text primary keys, app-supplied. domain.py generates prefixed ids
--       (e.g. "pack_ab12cd34ef56"); the DB accepts them rather than generating
--       its own, so the repository swap stays a drop-in for the in-memory repo.
--   D2  Embedded collections (sections, pre-read/challenge items, deep-dive
--       sources, job steps/log) are JSONB — they mirror the pydantic shapes
--       exactly, so the repo serialises with model_dump() and back with no
--       normalisation layer. Scalar string arrays (focus_areas, keywords) use
--       native text[]. Top-level entities are real tables with real FKs.
--   D3  Single-user namespace (A2): every row carries user_id DEFAULT
--       'single_user'. RLS is NOT enabled in v1 — the backend uses the service
--       role key, which bypasses RLS anyway. Policy templates are left commented
--       at the foot; enabling them is the RM-3 (multi-user) step, no schema
--       rewrite required (NFR-6).
--   D4  Deletion completeness (FR-LB-3/5, TR-INV-5): every pack-child FKs to
--       board_pack ON DELETE CASCADE, so `delete from board_pack` removes
--       chunks (incl. their vectors), pre-reads, challenge sheets, deep-dives,
--       run traces and jobs in one statement — no residue, no orphaned vectors.
--   D5  Ephemeral packs (FR-RT-3) are NEVER written here — the engine skips
--       persistence for retention_mode='ephemeral' (see engine.py). The column
--       exists for display/audit on persisted rows; every stored row is
--       'persist'. There is no sweep job because there is nothing to sweep.
--   D6  Lens is the authoritative table (FR-PR-4/5). §14.7 also lists
--       custom_lenses[] on UserSettings; that is denormalised. Here, custom
--       lenses are rows in `lens` where builtin=false, and user_settings holds
--       only a default_lens pointer. One source of truth. (Reconciliation item.)
--
-- ⚠️  ONE BLOCKING DECISION: the vector() dimension below (384) MUST match the
--     chosen local embedder (§12 open item). 384 = all-MiniLM-L6-v2 / BGE-small.
--     If you pick a 768-dim model (all-mpnet / BGE-base) change the single line
--     marked  << EMBEDDER DIMENSION >>  and nothing else.
-- ============================================================================

create extension if not exists vector;   -- pgvector, for PackChunk.embedding

-- ----------------------------------------------------------------------------
-- board_pack — the confidential input, sectioned (BoardPack, §7 / §14.7)
-- ----------------------------------------------------------------------------
create table board_pack (
    id              text primary key,                       -- D1, app-supplied
    user_id         text not null default 'single_user',    -- D3, NFR-6
    title           text not null,
    type            text not null default 'board_pack',     -- §14.7 E2 discriminator
    uploaded_at     timestamptz not null default now(),
    source_file_ref text,                                   -- FR-IN-3, Storage path
    sections        jsonb not null default '[]',            -- D2, list[PackSection]
                                                            --   (spec §7: "sectioned_content")
    retention_mode  text not null default 'persist'
                        check (retention_mode in ('persist', 'ephemeral')),  -- D5
    created_at      timestamptz not null default now()
);
comment on table board_pack is 'BoardPack (§7). The one module-boundary that holds raw confidential input.';

-- ----------------------------------------------------------------------------
-- pack_chunk — pack-derived MNPI; lives IN-ZONE only (PackChunk, §7)
--   Embeddings are generated by the LOCAL embedder (A5/FR-IN-8) and never leave
--   the zone. This table is the vector store (M4).
-- ----------------------------------------------------------------------------
create table pack_chunk (
    id          text primary key,                           -- D1
    pack_id     text not null references board_pack(id) on delete cascade,  -- D4
    user_id     text not null default 'single_user',        -- D3
    section_ref text not null,                               -- FR-IN-7 section reference
    chunk_text  text not null,                               -- MNPI — in-zone only
    embedding   vector(384),   -- << EMBEDDER DIMENSION >>  match to §12 model choice
    created_at  timestamptz not null default now()
);
comment on table pack_chunk is 'PackChunk (§7). Pack-derived MNPI + embeddings. In-zone only (INV-1).';

-- HNSW index for cosine similarity — sentence-transformers output is normalised,
-- so cosine is the right operator. Built empty; fills as packs are indexed.
create index pack_chunk_embedding_idx
    on pack_chunk using hnsw (embedding vector_cosine_ops);
create index pack_chunk_pack_id_idx on pack_chunk (pack_id);

-- ----------------------------------------------------------------------------
-- director_profile — shapes pre-read emphasis + challenge (DirectorProfile, §7)
-- ----------------------------------------------------------------------------
create table director_profile (
    id           text primary key,                          -- D1
    user_id      text not null default 'single_user',       -- D3
    committee    text not null default 'other'
                     check (committee in ('audit', 'risk', 'remuneration', 'other')),
                     -- NOTE (reconciliation): domain.py Committee enum is 4-valued,
                     -- but lenses (§14.4) span 7+ perspectives. `lens` is the richer
                     -- concept; `committee` is retained for the existing pre-read
                     -- emphasis path (nodes.py). Decide whether to fold committee
                     -- into lens or keep both — not blocking for this migration.
    focus_areas  text[] not null default '{}',              -- D2 scalar array
    depth        text not null default 'standard',
    bank_context text
);
comment on table director_profile is 'DirectorProfile (§7). Same object feeds pre-read and challenge (FR-PR-2).';

-- ----------------------------------------------------------------------------
-- pre_read — profile-shaped pre-read (PreRead, §7). Pack-derived only.
-- ----------------------------------------------------------------------------
create table pre_read (
    id           text primary key,                          -- D1
    pack_id      text not null references board_pack(id) on delete cascade,  -- D4
    profile_id   text references director_profile(id) on delete set null,
    user_id      text not null default 'single_user',       -- D3
    items        jsonb not null default '[]',               -- D2, list[PreReadItem]
                                                            --   items are individually
                                                            --   addressable via item_ref
                                                            --   (FR-PRE-3) inside the JSONB
    generated_at timestamptz not null default now()
);
comment on table pre_read is 'PreRead (§7). Derived from pack only, no external calls (FR-PRE-2).';

-- ----------------------------------------------------------------------------
-- challenge_sheet — profile-shaped challenge questions (ChallengeSheet, §7)
--   Each item carries source_item_ref linking back to a pre-read item / section
--   (FR-CH-2), stored inside the JSONB item objects.
-- ----------------------------------------------------------------------------
create table challenge_sheet (
    id           text primary key,                          -- D1
    pack_id      text not null references board_pack(id) on delete cascade,  -- D4
    profile_id   text references director_profile(id) on delete set null,
    user_id      text not null default 'single_user',       -- D3
    items        jsonb not null default '[]',               -- D2, each {..., source_item_ref}
    generated_at timestamptz not null default now()
);
comment on table challenge_sheet is 'ChallengeSheet (§7). Items link back to pre-read/section (FR-CH-2).';

-- ----------------------------------------------------------------------------
-- deep_dive — external synthesis anchored to an internal point (DeepDive, §7)
--   analysis + sources persist here; the RAW research-provider payload does NOT
--   (FR-GV-4) — it lives in the Langfuse trace only (see run_trace.trace_ref).
--   source_item_ref is the INTERNAL anchor ("Launched from"); sources[] are
--   EXTERNAL only, shape {url, snippet, retrieved_at} (FR-DD-5).
-- ----------------------------------------------------------------------------
create table deep_dive (
    id              text primary key,                       -- D1
    pack_id         text not null references board_pack(id) on delete cascade,  -- D4
    user_id         text not null default 'single_user',    -- D3
    question        text not null,                          -- FR-DD-1
    source_item_ref text,                                   -- FR-DD-7 internal anchor (nullable)
    analysis        text not null default '',               -- FR-DD-4 synthesised
    sources         jsonb not null default '[]',            -- D2, external {url,snippet,retrieved_at}
    created_at      timestamptz not null default now()
);
comment on table deep_dive is 'DeepDive (§7). Persists analysis + external sources only; raw payload is trace-only (FR-GV-4).';
create index deep_dive_pack_id_idx on deep_dive (pack_id);

-- ----------------------------------------------------------------------------
-- run_trace — governance / audit (RunTrace, §7; M10). Powers the Activity view.
--   firewall_query holds the EXACT external query for deep-dive runs (NFR-4);
--   null for non-deep-dive runs. trace_ref points at the Langfuse trace that
--   holds the raw payload (FR-GV-4).
-- ----------------------------------------------------------------------------
create table run_trace (
    id            text primary key,                         -- D1
    pack_id       text not null references board_pack(id) on delete cascade,  -- D4
    user_id       text not null default 'single_user',      -- D3
    run_type      text not null
                      check (run_type in ('ingest', 'preread', 'challenge', 'deepdive')),
    firewall_query text,                                    -- NFR-4, deep-dive only
    trace_ref     text,                                     -- Langfuse pointer
    created_at    timestamptz not null default now()
);
comment on table run_trace is 'RunTrace (§7, M10). Cross-cutting audit; Activity view reads this. Not on the confidential-to-external data path (FR-GV-3).';
create index run_trace_pack_id_idx on run_trace (pack_id);
create index run_trace_created_at_idx on run_trace (created_at desc);  -- Activity list order

-- ----------------------------------------------------------------------------
-- job — async processing job (Job, §14.7; M11). Backs the Processing screen.
--   State machine (FR-JOB-2): queued → parsing → indexing → drafting_preread
--   → drafting_challenge → ready | failed. percent is monotonic to 100.
-- ----------------------------------------------------------------------------
create table job (
    id         text primary key,                            -- D1
    pack_id    text references board_pack(id) on delete cascade,  -- D4 (nullable: pack
                                                            --   may not exist yet at queue time)
    user_id    text not null default 'single_user',         -- D3
    status     text not null default 'queued'
                   check (status in ('queued', 'parsing', 'indexing',
                                     'drafting_preread', 'drafting_challenge',
                                     'ready', 'failed')),    -- FR-JOB-2
    percent    int not null default 0 check (percent between 0 and 100),
    steps      jsonb not null default '[]',                 -- D2, [{name, state}]
    log        jsonb not null default '[]',                 -- D2, [{ts, message}] agentic log
    error      text,                                        -- FR-JOB-5 clear error on failure
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
comment on table job is 'Job (§14.7, M11). Async ingest+pre-read+challenge; streamed via SSE (NFR-8).';
create index job_status_idx on job (status);

-- ----------------------------------------------------------------------------
-- lens — committee perspective as emphasis keyword map (Lens, §14.7; FR-PR-4/5)
--   builtin=true: the standard set (seeded below). builtin=false: user customs.
-- ----------------------------------------------------------------------------
create table lens (
    id       text primary key,                              -- D1
    user_id  text not null default 'single_user',           -- D3
    name     text not null,
    keywords text[] not null default '{}',                  -- D2 scalar array (emphasis map)
    builtin  boolean not null default false
);
comment on table lens is 'Lens (§14.7). Adding one is configuration, not code (FR-PR-4). D6: authoritative over UserSettings.custom_lenses[].';

-- ----------------------------------------------------------------------------
-- user_settings — single row in v1 (UserSettings, §14.7). Profile defaults,
--   lenses pointer, branding (FR-SET), onboarding version.
-- ----------------------------------------------------------------------------
create table user_settings (
    id                     text primary key,                -- D1
    user_id                text not null unique default 'single_user',  -- D3, one row in v1
    default_lens           text references lens(id) on delete set null,  -- D6 pointer
    focus_areas            text[] not null default '{}',
    depth                  text not null default 'standard',
    accent                 text default '#003366',          -- FR-SET-1 (curated default)
    favicon_ref            text,                             -- FR-SET-2
    app_name               text not null default 'Board Preparation Dashboard',  -- FR-SET-2
    logo_ref               text,                             -- FR-SET-2
    onboarding_seen_version text                             -- FR-ONB-2
);
comment on table user_settings is 'UserSettings (§14.7). Branding doubles as white-label lever (FR-SET-4).';

-- ============================================================================
-- Seed data
-- ============================================================================

-- Standard lens set (§14.4). Keyword maps extend nodes.py _EMPHASIS with the
-- perspectives added in v1.3. Custom lenses are added by the user at runtime.
insert into lens (id, name, keywords, builtin) values
    ('lens_risk',        'Risk',                  '{risk,capital,credit,cet1,provision,liquidity}',           true),
    ('lens_audit',       'Audit',                 '{control,provision,audit,compliance,restatement}',         true),
    ('lens_remuneration','Remuneration',          '{remuneration,pay,incentive,bonus,compensation}',          true),
    ('lens_nomination',  'Nomination/Governance', '{governance,board,succession,nomination,composition}',     true),
    ('lens_fullboard',   'Full board',            '{}',                                                       true),
    ('lens_techcyber',   'Technology/Cyber',      '{cyber,technology,resilience,vulnerability,infrastructure}', true),
    ('lens_esg',         'ESG',                   '{esg,sustainability,emissions,scope,climate}',             true);

-- Single-user settings row (A2). Defaults to Full board, standard depth,
-- the curated primary accent, and the canonical app name.
insert into user_settings (id, user_id, default_lens, depth, accent, app_name)
values ('settings_singleton', 'single_user', 'lens_fullboard', 'standard', '#003366', 'Board Preparation Dashboard');

-- ============================================================================
-- Multi-user readiness (NFR-6 / RM-3) — TEMPLATE, intentionally NOT enabled.
-- ----------------------------------------------------------------------------
-- v1 has no auth (A2) and the backend uses the service role key, so RLS would
-- be bypassed regardless. When auth lands, enable RLS per table and swap
-- 'single_user' for auth.uid(). No schema change needed — only these policies.
--
--   alter table board_pack enable row level security;
--   create policy board_pack_owner on board_pack
--       using (user_id = auth.uid()::text)
--       with check (user_id = auth.uid()::text);
--   -- ...repeat per table (pack_chunk, director_profile, pre_read,
--   --    challenge_sheet, deep_dive, run_trace, job, lens, user_settings).
-- ============================================================================