"""Provider contracts (NFR-2: everything below is swappable behind these)."""
from __future__ import annotations
from typing import Protocol, runtime_checkable

from app.domain import (
    BoardPack, ChallengeSheet, DeepDive, DirectorProfile, Job, Lens,
    PackChunk, PreRead, RunTrace, Source, UserSettings,
)


@runtime_checkable
class PackParser(Protocol):
    """M3 Ingestion. Swap: PyPdfParser (now) -> Docling (prod)."""
    def parse(self, raw: bytes, title: str) -> BoardPack: ...


@runtime_checkable
class Retriever(Protocol):
    """M4 Retrieval index. Swap: LocalRetriever (now) -> local embedder + pgvector."""
    def index(self, pack: BoardPack) -> list[PackChunk]: ...
    def retrieve(self, pack_id: str, query: str, k: int = 4) -> list[PackChunk]: ...
    def drop(self, pack_id: str) -> None: ...


@runtime_checkable
class Inference(Protocol):
    """Shared inference. Swap: StubInference (now) -> DeepSeek via API."""
    def complete(self, system: str, user: str) -> str: ...


@runtime_checkable
class QueryFirewall(Protocol):
    """M7 Query firewall. Sole exit to external search (FR-FW-3). Intent only, never chunks."""
    def formulate(self, intent: str) -> str: ...


@runtime_checkable
class ResearchProvider(Protocol):
    """M8 Research module. Swap: StubResearch (now) -> Tavily. Outside the zone."""
    def search(self, query: str) -> list[Source]: ...


@runtime_checkable
class Repository(Protocol):
    """M9 Persistence substrate. Swap: InMemoryRepository (now) -> Supabase."""
    def save_pack(self, pack: BoardPack) -> None: ...
    def get_pack(self, pack_id: str) -> BoardPack | None: ...
    def list_packs(self) -> list[BoardPack]: ...
    def delete_pack(self, pack_id: str) -> None: ...

    def save_profile(self, profile: DirectorProfile) -> None: ...
    def get_profile(self, profile_id: str) -> DirectorProfile | None: ...

    def save_preread(self, preread: PreRead) -> None: ...
    def get_preread(self, pack_id: str) -> PreRead | None: ...

    def save_challenge(self, challenge: ChallengeSheet) -> None: ...
    def get_challenge(self, pack_id: str) -> ChallengeSheet | None: ...

    def save_deepdive(self, deepdive: DeepDive) -> None: ...
    def list_deepdives(self, pack_id: str) -> list[DeepDive]: ...
    def delete_deepdive(self, deepdive_id: str) -> None: ...

    def save_lens(self, lens: Lens) -> None: ...
    def get_lens(self, lens_id: str) -> Lens | None: ...
    def list_lenses(self) -> list[Lens]: ...
    def delete_lens(self, lens_id: str) -> None: ...

    def save_job(self, job: Job) -> None: ...
    def get_job(self, job_id: str) -> Job | None: ...
    def list_jobs(self) -> list[Job]: ...

    def save_runtrace(self, trace: RunTrace) -> None: ...
    def list_runtraces(self, pack_id: str) -> list[RunTrace]: ...
    def list_all_runtraces(self) -> list[RunTrace]: ...

    def get_settings(self) -> UserSettings: ...
    def save_settings(self, s: UserSettings) -> None: ...